### ISSUE TITLE
error parsing map: tiled: invalid decoded tile countexit status 2

### ISSUE THREAD

**Issue by lidldev** [lafriks/go-tiled#85]
Hey, I decided to use go-tiled for a project of mine by using ebitenengine, I designed my map and put it where it should be as a .tmx file, but now I'm getting this error.

---------------------------------

* With this code, I can convert the .tmx format to an image and print it to the screen. I tried it once, but after that, I kept getting the error in the title while trying.
```go
func getTiled(name string) *ebiten.Image {
	gameMap, err := tiled.LoadFile(name)
	if err != nil {
		fmt.Printf("error parsing map: %s", err.Error())
		os.Exit(2)
	}

	fmt.Println(gameMap)

	renderer, err := render.NewRenderer(gameMap)
	if err != nil {
		fmt.Printf("map unsupported for rendering: %s", err.Error())
		os.Exit(2)
	}

	// Render just layer 0 to the Renderer.
	err = renderer.RenderLayer(0)
	if err != nil {
		fmt.Printf("layer unsupported for rendering: %s", err.Error())
		os.Exit(2)
	}

	// Get a reference to the Renderer's output, an image.NRGBA struct.
	img := renderer.Result

	// Clear the render result after copying the output if separation of
	// layers is desired.

        renderer.Clear()

	return ebiten.NewImageFromImage(img)
}
``` 

-------------------------

* I get the .tmx file with this global variable
```go
var Tile = getTiled("./assets/Sprites/tile.tmx")
```

<img width="179" alt="Screenshot 2024-04-07 at 17 56 33" src="https://github.com/lafriks/go-tiled/assets/118509044/a6810fcf-e398-429f-8054-dc7a8ae4f790">

--------------------------

* this is the inside of my .tmx file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.10" tiledversion="1.10.2" orientation="orthogonal" renderorder="right-down" width="120" height="68" tilewidth="16" tileheight="16" infinite="1" nextlayerid="2" nextobjectid="1">
 <tileset firstgid="1" source="tilemap.tsx"/>
 <layer id="1" name="Tile Layer 1" width="120" height="68">
  <data encoding="csv">
   <chunk x="-16" y="-16" width="16" height="16">
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,5,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,17,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,17
</chunk>
   <chunk x="0" y="-16" width="16" height="16">
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,5,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,17,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
</chunk>
   <chunk x="-16" y="0" width="16" height="16">
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,5,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,17,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
</chunk>
   <chunk x="0" y="0" width="16" height="16">
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,5,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,17,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,5,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,17,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
</chunk>
  </data>
 </layer>
</map>
```

**Comment by lafriks** [comment]
Do I understand correctly - it works for the first time but on the second time loading tmx file fails with an error?

**Comment by lidldev** [comment]
> Do I understand correctly - it works for the first time but on the second time loading tmx file fails with an error?

At first I was able to draw on the screen properly, but after changing a few things I started getting this error.

**Comment by lafriks** [comment]
Can you share also tilemap so I could reproduce this?

**Comment by lidldev** [comment]
> Can you share also tilemap so I could reproduce this?

[](https://github.com/lidldev/MysteryGame) all files in here

**Comment by lidldev** [comment]
I commented and deleted the ``os.Exit(2)`` code in the if statement, which detected an error in the existing code, and I started getting another error.

```cmd
ahmetaffanebcioglu@192 MysteryGame % go run main.go
error parsing map: tiled: invalid decoded tile count<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x100663264]

goroutine 1 [running, locked to thread]:
github.com/lafriks/go-tiled/render.NewRendererWithFileSystem(0x0, {0x0, 0x0})
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:76 +0x84
github.com/lafriks/go-tiled/render.NewRenderer(...)
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:70
main/assets.getTiled({0x1007b297a?, 0x100c96080?})
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:124 +0xd8
main/assets.init()
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:26 +0x98
exit status 2
ahmetaffanebcioglu@192 MysteryGame % go run main.go
error parsing map: strconv.ParseUint: parsing "16161616133": value out of range<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x100362a24]

goroutine 1 [running, locked to thread]:
github.com/lafriks/go-tiled/render.NewRendererWithFileSystem(0x0, {0x0, 0x0})
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:76 +0x84
github.com/lafriks/go-tiled/render.NewRenderer(...)
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:70
main/assets.getTiled({0x1004b213a?, 0x100996080?})
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:124 +0xd8
main/assets.init()
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:26 +0x98
exit status 2
ahmetaffanebcioglu@192 MysteryGame %   
 *  History restored 

ahmetaffanebcioglu@192 MysteryGame % go run main.go
error parsing map: strconv.ParseUint: parsing "16161616133": value out of range<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x1011aea24]

goroutine 1 [running, locked to thread]:
github.com/lafriks/go-tiled/render.NewRendererWithFileSystem(0x0, {0x0, 0x0})
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:76 +0x84
github.com/lafriks/go-tiled/render.NewRenderer(...)
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:70
main/assets.getTiled({0x1012fe13a?, 0x1017e2080?})
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:124 +0xd8
main/assets.init()
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:26 +0x98
exit status 2
ahmetaffanebcioglu@192 MysteryGame % git add .
ahmetaffanebcioglu@192 MysteryGame % git commit -m "noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo0"

[main 7bbed6d] noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo0
 3 files changed, 68 insertions(+), 68 deletions(-)
 rename assets/Sprites/{tilemap.tsx => tilemap_packed.tsx} (100%)
ahmetaffanebcioglu@192 MysteryGame % git push
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 966 bytes | 966.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/lidldev/MysteryGame.git
   2acdc35..7bbed6d  main -> main
ahmetaffanebcioglu@192 MysteryGame % go run main.go
error parsing map: strconv.ParseUint: parsing "16161616133": value out of range<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x100a2aa24]

goroutine 1 [running, locked to thread]:
github.com/lafriks/go-tiled/render.NewRendererWithFileSystem(0x0, {0x0, 0x0})
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:76 +0x84
github.com/lafriks/go-tiled/render.NewRenderer(...)
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:70
main/assets.getTiled({0x100b7a13a?, 0x10105e080?})
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:124 +0xd8
main/assets.init()
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:26 +0x98
exit status 2
ahmetaffanebcioglu@192 MysteryGame % go run main.go
error parsing map: strconv.ParseUint: parsing "16161616133": value out of range<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x100be6a24]

goroutine 1 [running, locked to thread]:
github.com/lafriks/go-tiled/render.NewRendererWithFileSystem(0x0, {0x0, 0x0})
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:76 +0x84
github.com/lafriks/go-tiled/render.NewRenderer(...)
        /Users/ahmetaffanebcioglu/go/pkg/mod/github.com/lafriks/go-tiled@v0.12.0/render/renderer.go:70
main/assets.getTiled({0x100d3613a?, 0x10121a080?})
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:124 +0xd8
main/assets.init()
        /Users/ahmetaffanebcioglu/Documents/Nuclear-Launch-Codes/MysteryGame/assets/assets.go:26 +0x98
exit status 2
```

**Comment by SolarLune** [comment]
It looks like this error (for whatever reason) is due to your map being infinite. After changing the map to be finite in size (in the Map Properties pane on the left-hand side of the map editor, underneath tile width and height), I was able to get it to work.

@lafriks It might be good to add a note to the readme that go-tiled supports orthogonal, finite maps only at the moment.

**Comment by lidldev** [comment]
It was fixed when I changed it to finite instead of infinite. @SolarLune @lafriks
